
document.addEventListener('DOMContentLoaded', () => {
    const translations = {
        english: {

            // Navbar //

            navbar_1_title: "Cities in Malaysia",
            navbar_1_1: "Kuala Lumpur",
            navbar_1_2: "Johor Bahru",
            navbar_1_3: "Langkawi",
            navbar_1_4: "Melaka",
            navbar_1_5: "Penang",
            navbar_2_title: "Attractions",
            navbar_2_1: "Aquaria KLCC",
            navbar_2_2: "Check availability",
            navbar_2_3: "Genting Awana SkyWay",
            navbar_2_4: "KL Tower",
            navbar_2_5: "Petronas Twin Towers",
            navbar_2_6: "Entopia Penang",
            navbar_2_7: "Langkawi Underwater World",
            navbar_2_8: "3D Trick Art Museum",
            navbar_2_9: "The Habitat Penang Hill",
            navbar_2_10: "Dark Mansion Museum",
            navbar_2_11: "Wonderfood Museum",
            navbar_2_12: "Langkawi SkyCab Cable Car",
            navbar_2_13: "Batu Caves",
            navbar_2_14: "Melaka Zoo",
            navbar_2_15: "LEGOLAND Malaysia",
            navbar_2_16: "Sunway Lagoon Theme Park",
            navbar_2_17: "Escape Theme Park",
            navbar_2_18: "Lost World of Tambun",
            navbar_2_29: "Crocodile Adventureland Langkawi",
            navbar_2_20: "KidZania Kuala Lumpur",
            navbar_2_21: "Ripley's Adventureland",
            navbar_2_22: "Desaru Coast Adventure Waterpark",
            navbar_2_23: "KL Tower Mini Zoo",
            navbar_2_24: "Genting Skyworlds Theme Park",
            navbar_2_25: "Genting Skytropolis Theme Park",

            // Navbar //


            // Home_tickets //

            home_title_1: "Top Attractions In Malaysia",
            ticket_1: "Sunway Lagoon Theme Park",
            ticket_2: "Menara Kuala Lumpur Tower Tickets (KL Tower)",
            ticket_3: "Aquaria KLCC",
            ticket_4: "Gamuda Cove",
            ticket_5: "petronas twin towers",
            ticket_6: "Genting Skyworlds Theme Park",
            ticket_7: "A'famosa Water Park",
            ticket_8: "The Top Penang",
            ticket_9: "Check availability",
            ticket_10: "Wet World Water Park",
            ticket_11: "Genting Skytropolis Theme Park",
            ticket_12: "Lost World of Tambun Amusement Park",
            ticket_13: "Mari Mari Cultural Village",
            ticket_14: "atmosphere 360",
            ticket_15: "Genting Awana SkyWay",
            ticket_16: "Langkawi SkyCab Cable Car",
            ticket_17: "Batu Caves",
            ticket_18: "Upside Down House",
            ticket_19: "The Habitat Penang Hill",
            ticket_20: "Fireflies in Kuala Selangor",
            ticket_21: "Sky Mirror",
            ticket_22: "Taming Sari Melaka",
            ticket_23: "The Shore Sky Tower",
            ticket_24: "KL City Tours",
            ticket_25: "Blue Tears Tour in Kuala Selangor",
            ticket_26: "Colmar Tropicale",
            ticket_27: "Langkawi Tours",
            ticket_28: "Eagle-feeding Kuala Selangor",
            ticket_29: "Petrosains, The Discovery Centre",
            home_title_2: "Find out all the top attractions and the",
            home_title_3: "best theme parks in Malaysia",
            home_title_4: "Nature & Wildlife in Malaysia",
            ticket_30: "Zoo Negara",
            ticket_31: "KL Bird Park",
            ticket_32: "Melaka Zoo",
            ticket_33: "KL Tower Mini Zoo",
            ticket_34: "Crocodile Adventureland Langkawi",
            ticket_35: "Farm in the City",
            ticket_36: "Bentong Farm",
            ticket_37: "Langkawi Underwater World",
            ticket_38: "Entopia by Penang Butterfly Farm",
            ticket_39: "Taman Buaya & Rekreasi Melaka",
            home_title_5: "Best Theme Parks & Water Parks in Malaysia",
            ticket_40: "Berjaya Times Square Theme Park",
            ticket_41: "LEGOLAND Malaysia",
            ticket_42: "Bayou Lagoon Water Park",
            ticket_43: "99 Wonderland Park",
            ticket_44: "KidZania Kuala Lumpur Tickets",
            ticket_45: "VR Universal",
            ticket_46: "Escape Theme Park",
            ticket_47: "Desaru Coast Adventure Waterpark",
            ticket_48: "Bukit Merah Water Park",
            ticket_49: "Ehsan Waterpark",
            ticket_50: "I-City Theme Park",
            ticket_51: "Splash Out Langkawi",
            home_title_6: "Museums in Malaysia",
            ticket_52: "Wonderfood Museum",
            ticket_53: "Illusion 3D Art Museum",
            ticket_54: "Penang 3D Trick Art Museum",
            ticket_55: "Dark Mansion Museum",
            ticket_56: "Tech Dome Penang",
            ticket_57: "Ghost Museum Melaka",
            ticket_58: "Ripley's Adventureland",
            ticket_59: "Ghost Museum Penang",
            home_title_7: "Popular Activities in Malaysia",
            ticket_60: "Kiulu White Water Rafting",
            ticket_61: "xtreme park langkawi",
            ticket_62: "Jump Street Asia",
            ticket_63: "ATV Langkawi",
            ticket_64: "Langkawi Island Hopping",
            home_title_8: "Malaysia Cruises",
            ticket_65: "Dickson Dragon Cruise",
            ticket_66: "Putrajaya Tour & Cruise",
            home_title_9: "Transportation Services",
            ticket_67: "KLIA Express Tickets",
            ticket_68: "Langkawi Ferry Tickets & Transfers",
            ticket_69: "Malaysia Airport Transfers",

            // Home_tickets //


            // Footer // 

            footer_1: "Download the Headout app",
            footer_2: "Get Help 24/7",
            footer_3: "Chat with Us",
            footer_4: "Call Us",
            footer_5: "Email Us",
            footer_6: "Headout",
            footer_7: "Company Details",
            footer_8: "Privacy Policy",
            footer_9: "Terms of Usage",
            footer_10: "We Accept",
            footer_11: "© Headout Inc, 82 Nassau St #60351 New York, NY 10038",

            // Footer // 


            // SunwayLagoon.html //


            show_inclusions: "Check availability",
            sunway_ticket_check_availability: "Check availability",
            sunway_ticket_next_available: "Next available: Today",
            sunway_ticket_Mobile_ticket: "Mobile ticket",
            sunway_ticket_Flexible_Duration: "Flexible Duration",
            sunway_ticket_Meals_Included: "Meals Included",
            sunway_title: "Sunway Lagoon Theme Park Tickets",
            sunway_rating: "(6.5K Ratings)",
            sunway_header_p: "Headout is an authorized and trusted partner of the venue, offering curated experiences to enjoy this attraction. This is not the venue's website.",
            tickets: "TICKETS",
            combos: "COMBOS",
            sunway_ticket_from: "from",

            sunway_ticket_1_title: "Sunway Lagoon Theme Park Tickets",
            sunway_ticket_1_description_1: "Looking for an adventurous and fun-filled afternoon with your family? Visit Sunway Lagoon, which offers something for every age and preference.",
            sunway_ticket_1_description_2: "Swing by up to 90 rides and attractions, including the Vuvuzela, one of the world's highest water rides, the topsy-turvy Tomahawk, and more.",
            sunway_ticket_1_description_3: "Explore the 6 exhilarating zones, including Water Park, Amusement Park, Extreme Park, Wildlife Park, Scream Park, and the Nickelodeon Lagoon.",
            sunway_ticket_1_description_4: "Enjoy complimentary access to the Night Park, featuring attractions, activities in an Old American West-themed setting, and fire performances.",
            sunway_ticket_1_description_5: "Enhance your experience with optional priority access to 21 rides, or choose a 2-day pass with meals, camping, and a discount on pay-per-rides.",
            sunway_ticket_1_skidka: "15% off",

            sunway_ticket_2_title: "Tickets to Sunway Lagoon Night Park",
            sunway_ticket_2_description_1: "Get ready for a wild night in Sunway Lagoon Night Park, where you'll get to experience the Old American West with thrilling cowboy-themed attractions and activities!",
            sunway_ticket_2_description_2: "Enjoy spectacular fire performances and stunning visuals as you get into the spirit of the Wild West",
            sunway_ticket_2_description_3: "Test your courage and skills on the Rodeo Bull ride and enjoy the Grand Canyon River Rapid.",
            sunway_ticket_2_description_4: "Experience the Wild West Mingle show with live performances and entertainment, and end the day with the night's finale, the spectacular fire performance",
            sunway_ticket_2_skidka: "13% off",

            sunway_ticket_3_title: "Combo (Save 17%): Aquaria KLCC + Sunway Lagoon Tickets",
            sunway_ticket_3_description_1: "Visit two of Kuala Lumpur's most popular attractions, Aquaria KLCC and Sunway Lagoon, with just one money-saving combo ticket.",
            sunway_ticket_3_description_2: "At Aquaria KLCC, you can immerse yourself in the worlds of terrestrial and aquatic life, with over 5,000 creatures on show.",
            sunway_ticket_3_description_3: "See amazing exhibits including the Jewels of the Jungle, Deep Forest, Touch Pool, and Evolution Zone.",
            sunway_ticket_3_description_4: "W walk along the 90-meter-long underwater walkway for breathtaking views of the marine animals in their habitat and don't miss the daily feeding activities.",
            sunway_ticket_3_skidka: "17% off",

            sunway_ticket_4_title: "Combo (Save 13%): Sunway Lagoon Theme Park + Zoo Negara & Panda Conservation Centre Tickets",
            sunway_ticket_4_description_1: "Save money on this exciting combo that gives you access to the thrills of Sunway Lagoon Park and the friendly residents of Zoo Negara.",
            sunway_ticket_4_description_2: "Spend your day exploring over 90 attractions at one of Malaysia’s most iconic theme parks, Sunway Lagoon.",
            sunway_ticket_4_description_3: "Get to enjoy the water park, amusement park, extreme park, wildlife park, scream park, and the Nickelodeon Lagoon.",
            sunway_ticket_4_description_4: "Stroll through 110 acres of lush greenery plot waving at 476 species of mammals, birds, reptiles, amphibians, and fish.",
            sunway_ticket_4_description_5: "Discover more about each species at the Panda Centre, Reptile House, Bear Complex, Savannah Walk, and the Mammal Kingdom.",
            sunway_ticket_4_skidka: "18% off",

            sunway_ticket_5_title: "Sunway Lagoon Ticket with Private Round Trip Transfers",
            sunway_ticket_5_description_1: "Sunway Lagoon, the sprawling entertainment destination in Selangor, has something for everyone. Bring your A-game, with round-trip hotel transfers.",
            sunway_ticket_5_description_2: "With this ticket, access 6 parks – Water Park, Amusement Park, Wildlife Park, Extreme Park, Scream Park & Nickelodeon Lost Lagoon.",
            sunway_ticket_5_description_3: "These parks are home to the highest slingshot ride in Asia and the longest flying fox trail in Malaysia, as well as the country’s first interactive zoo.",
            sunway_ticket_5_description_4: "It also has an artificial beach to complete the entire surf’s up experience - with an impressive 13,000m² pool area where guests can surf.",
            sunway_ticket_5_description_5: "The Wave Pool uses patented hydraulic systems to create massive waves up to 9 feet in height.",
            sunway_ticket_5_skidka: "",

            sunway_ticket_6_title: "Combo (Save 15%): Sunway Lagoon Theme Park + KL Hop-On Hop-Off Sightseeing Bus Tour",
            sunway_ticket_6_description_1: "Unlock savings with a Sunway Lagoon Theme Park and hop-on-hop-off sightseeing tour combo, merging thrills and city exploration on a budget.",
            sunway_ticket_6_description_2: "Experience excitement at Sunway Lagoon Theme Park, featuring 6 unique parks, including Nickelodeon Lagoon, Scream Park, Extreme Park, and more.",
            sunway_ticket_6_description_3: "Befriend the friendly and ferocious wildlife, enjoy water adventures, and hop on exciting rides like Pirate's Revenge and Congo Challenge.",
            sunway_ticket_6_description_4: "Explore Kuala Lumpur with a hop-on-hop-off tour of 27 stops, providing flexibility to customize your itinerary and discover the city in just 1 day.",
            sunway_ticket_6_description_5: "Enjoy the metropolitan skyline from an open-top double-decker bus, accompanied by live commentary, and disembark wherever your curiosity leads you.",
            sunway_ticket_6_skidka: "15% off",

            


            // SunwayLagoon.html //


            // Tickets_select //


            for_tickets_select: "Select",

            for_tickets_1_1_title: "General Admission:Malaysian Citizens",
            for_tickets_1_1_skidka: "Save up to 6%",
            for_tickets_1_1_1_description: "Entry to Sunway Lagoon",
            for_tickets_1_1_2_description: "Access to Night Park",
            for_tickets_1_1_3_description: "Access to all rides",

            for_tickets_1_2_title: "General Admission:Non-Malaysian Citizens",
            for_tickets_1_2_skidka: "Save up to 15%",
            for_tickets_1_2_1_description: "Entry to Sunway Lagoon",
            for_tickets_1_2_2_description: "Access to Night Park",
            for_tickets_1_2_3_description: "Access to all rides",

            for_tickets_1_3_title: "General Admission + Quack Xpress Pass: Malaysian Citizens",
            for_tickets_1_3_skidka: "Save up to 6%",
            for_tickets_1_3_1_description: "Priority access to 21 rides",
            for_tickets_1_3_2_description: "Entry to Sunway Lagoon",
            for_tickets_1_3_3_description: "Access to Night Park",
            for_tickets_1_3_4_description: "Access to all rides",

            bookaquaria_ticket_1: '',

            for_1_pro: "1% off",
            for_2_pro: "2% off",
            for_3_pro: "3% off",
            for_4_pro: "4% off",
            for_5_pro: "5% off",
            for_6_pro: "6% off",
            for_7_pro: "7% off",
            for_8_pro: "8% off",
            for_9_pro: "9% off",
            for_10_pro: "10% off",
            for_11_pro: "11% off",
            for_12_pro: "12% off",
            for_13_pro: "13% off",
            for_14_pro: "14% off",
            for_15_pro: "15% off",
            for_16_pro: "16% off",
            for_17_pro: "17% off",
            for_18_pro: "18% off",
            for_19_pro: "19% off",
            for_20_pro: "20% off",
            for_21_pro: "21% off",
            for_22_pro: "22% off",
            for_23_pro: "23% off",
            for_24_pro: "24% off",
            for_25_pro: "25% off",
            for_26_pro: "26% off",
            for_27_pro: "27% off",
            for_28_pro: "28% off",
            for_29_pro: "29% off",
            for_30_pro: "30% off",
            for_31_pro: "31% off",
            for_32_pro: "32% off",
            for_33_pro: "33% off",
            for_34_pro: "34% off",
            for_35_pro: "35% off",
            for_36_pro: "36% off",
            for_37_pro: "37% off",
            for_38_pro: "38% off",
            for_39_pro: "39% off",
            for_40_pro: "40% off",
            for_41_pro: "41% off",
            for_42_pro: "42% off",
            for_43_pro: "43% off",
            for_44_pro: "44% off",
            for_45_pro: "45% off",
            for_46_pro: "46% off",
            for_47_pro: "47% off",
            for_48_pro: "48% off",
            for_49_pro: "49% off",
            for_50_pro: "50% off",
            for_51_pro: "51% off",
            for_52_pro: "52% off",
            for_53_pro: "53% off",
            for_54_pro: "54% off",
            for_55_pro: "55% off",
            for_56_pro: "56% off",
            for_57_pro: "57% off",
            for_58_pro: "58% off",
            for_59_pro: "59% off",
            for_60_pro: "60% off",
            for_61_pro: "61% off",
            for_62_pro: "62% off",
            for_63_pro: "63% off",
            for_64_pro: "64% off",
            for_65_pro: "65% off",
            for_66_pro: "66% off",
            for_67_pro: "67% off",
            for_68_pro: "68% off",
            for_69_pro: "69% off",
            for_70_pro: "70% off",
            for_71_pro: "71% off",
            for_72_pro: "72% off",
            for_73_pro: "73% off",
            for_74_pro: "74% off",
            for_75_pro: "75% off",
            for_76_pro: "76% off",
            for_77_pro: "77% off",
            for_78_pro: "78% off",
            for_79_pro: "79% off",
            for_80_pro: "80% off",
            for_81_pro: "81% off",
            for_82_pro: "82% off",
            for_83_pro: "83% off",
            for_84_pro: "84% off",
            for_85_pro: "85% off",
            for_86_pro: "86% off",
            for_87_pro: "87% off",
            for_88_pro: "88% off",
            for_89_pro: "89% off",
            for_90_pro: "90% off",
            for_91_pro: "91% off",
            for_92_pro: "92% off",
            for_93_pro: "93% off",
            for_94_pro: "94% off",
            for_95_pro: "95% off",
            for_96_pro: "96% off",
            for_97_pro: "97% off",
            for_98_pro: "98% off",
            for_99_pro: "99% off",
            for_100_pro: "100% off",

            for_bentong_farm: 'Book Farm in the City Malaysia Tickets & Tours',


        },
        indonesian: {

            for_bentong_farm: 'Pesan Tiket & Tur Pertanian di Kota Malaysia',

            for_14_pro: "diskon 14%",

            for_1_pro: "diskon 1%",
            for_2_pro: "diskon 2%",
            for_3_pro: "diskon 3%",
            for_4_pro: "diskon 4%",
            for_5_pro: "diskon 5%",
            for_6_pro: "diskon 6%",
            for_7_pro: "diskon 7%",
            for_8_pro: "diskon 8%",
            for_9_pro: "diskon 9%",
            for_10_pro: "diskon 10%",
            for_11_pro: "diskon 11%",
            for_12_pro: "diskon 12%",
            for_13_pro: "diskon 13%",
            for_14_pro: "diskon 14%",
            for_15_pro: "diskon 15%",
            for_16_pro: "diskon 16%",
            for_17_pro: "diskon 17%",
            for_18_pro: "diskon 18%",
            for_19_pro: "diskon 19%",
            for_20_pro: "diskon 20%",
            for_21_pro: "diskon 21%",
            for_22_pro: "diskon 22%",
            for_23_pro: "diskon 23%",
            for_24_pro: "diskon 24%",
            for_25_pro: "diskon 25%",
            for_26_pro: "diskon 26%",
            for_27_pro: "diskon 27%",
            for_28_pro: "diskon 28%",
            for_29_pro: "diskon 29%",
            for_30_pro: "diskon 30%",
            for_31_pro: "diskon 31%",
            for_32_pro: "diskon 32%",
            for_33_pro: "diskon 33%",
            for_34_pro: "diskon 34%",
            for_35_pro: "diskon 35%",
            for_36_pro: "diskon 36%",
            for_37_pro: "diskon 37%",
            for_38_pro: "diskon 38%",
            for_39_pro: "diskon 39%",
            for_40_pro: "diskon 40%",
            for_41_pro: "diskon 41%",
            for_42_pro: "diskon 42%",
            for_43_pro: "diskon 43%",
            for_44_pro: "diskon 44%",
            for_45_pro: "diskon 45%",
            for_46_pro: "diskon 46%",
            for_47_pro: "diskon 47%",
            for_48_pro: "diskon 48%",
            for_49_pro: "diskon 49%",
            for_50_pro: "diskon 50%",
            for_51_pro: "diskon 51%",
            for_52_pro: "diskon 52%",
            for_53_pro: "diskon 53%",
            for_54_pro: "diskon 54%",
            for_55_pro: "diskon 55%",
            for_56_pro: "diskon 56%",
            for_57_pro: "diskon 57%",
            for_58_pro: "diskon 58%",
            for_59_pro: "diskon 59%",
            for_60_pro: "diskon 60%",
            for_61_pro: "diskon 61%",
            for_62_pro: "diskon 62%",
            for_63_pro: "diskon 63%",
            for_64_pro: "diskon 64%",
            for_65_pro: "diskon 65%",
            for_66_pro: "diskon 66%",
            for_67_pro: "diskon 67%",
            for_68_pro: "diskon 68%",
            for_69_pro: "diskon 69%",
            for_70_pro: "diskon 70%",
            for_71_pro: "diskon 71%",
            for_72_pro: "diskon 72%",
            for_73_pro: "diskon 73%",
            for_74_pro: "diskon 74%",
            for_75_pro: "diskon 75%",
            for_76_pro: "diskon 76%",
            for_77_pro: "diskon 77%",
            for_78_pro: "diskon 78%",
            for_79_pro: "diskon 79%",
            for_80_pro: "diskon 80%",
            for_81_pro: "diskon 81%",
            for_82_pro: "diskon 82%",
            for_83_pro: "diskon 83%",
            for_84_pro: "diskon 84%",
            for_85_pro: "diskon 85%",
            for_86_pro: "diskon 86%",
            for_87_pro: "diskon 87%",
            for_88_pro: "diskon 88%",
            for_89_pro: "diskon 89%",
            for_90_pro: "diskon 90%",
            for_91_pro: "diskon 91%",
            for_92_pro: "diskon 92%",
            for_93_pro: "diskon 93%",
            for_94_pro: "diskon 94%",
            for_95_pro: "diskon 95%",
            for_96_pro: "diskon 96%",
            for_97_pro: "diskon 97%",
            for_98_pro: "diskon 98%",
            for_99_pro: "diskon 99%",
            for_100_pro: "diskon 100%",

            navbar_1_title: "Kota-kota di Malaysia",
            navbar_1_1: "Kuala Lumpur",
            navbar_1_2: "Johor Bahru",
            navbar_1_3: "Langkawi",
            navbar_1_4: "Malaka",
            navbar_1_5: "Pulau Pinang",
            navbar_2_title: "Atraksi",
            navbar_2_1: "Akuarium KLCC",
            navbar_2_2: "Cek Ketersediaan",
            navbar_2_3: "Genting Awana SkyWay",
            navbar_2_4: "Menara KL",
            navbar_2_5: "Menara Kembar Petronas",
            navbar_2_6: "Entopia Penang",
            navbar_2_7: "Dunia Bawah Laut Langkawi",
            navbar_2_8: "Museum Seni Trik 3D",
            navbar_2_9: "Habitat Bukit Penang",
            navbar_2_10: "Museum Rumah Gelap",
            navbar_2_11: "Museum Makanan Ajaib",
            navbar_2_12: "Kereta Gantung Langkawi SkyCab",
            navbar_2_13: "Gua Batu",
            navbar_2_14: "Kebun Binatang Melaka",
            navbar_2_15: "LEGOLAND Malaysia",
            navbar_2_16: "Sunway Lagoon Theme Park",
            navbar_2_17: "Taman Hiburan Escape",
            navbar_2_18: "Dunia Tambun yang Hilang",
            navbar_2_29: "Petualangan Buaya Langkawi",
            navbar_2_20: "KidZania Kuala Lumpur",
            navbar_2_21: "KidZania Kuala Lumpur",
            navbar_2_22: "Taman Air Petualangan Pantai Desaru",
            navbar_2_23: "Kebun Binatang Mini Menara KL",
            navbar_2_24: "Taman Hiburan Genting Skyworlds",
            navbar_2_25: "Taman Hiburan Genting Skytropolis",
            home_title_1: "Atraksi Teratas Di Malaysia",
            ticket_1: "Taman Hiburan Sunway Lagoon",
            ticket_2: "Tiket Menara Kuala Lumpur (Menara KL)",
            ticket_3: "Akuarium KLCC",
            ticket_4: "Teluk Gamuda",
            ticket_5: "menara kembar petronas",
            ticket_6: "Taman Hiburan Genting Skyworlds",
            ticket_7: "Taman Air A'famosa",
            ticket_8: "Penang Teratas",
            ticket_9: "Cek Ketersediaan",
            ticket_10: "Taman Air Dunia Basah",
            ticket_11: "Taman Hiburan Genting Skytropolis",
            ticket_12: "Taman Hiburan Dunia Hilang Tambun",
            ticket_13: "Desa Budaya Mari Mari",
            ticket_14: "suasana 360",
            ticket_15: "Genting Awana SkyWay",
            ticket_16: "Kereta Gantung Langkawi SkyCab",
            ticket_17: "Gua Batu",
            ticket_18: "Rumah Terbalik",
            ticket_19: "Habitat Bukit Penang",
            ticket_20: "Kunang-kunang di Kuala Selangor",
            ticket_21: "Cermin Langit",
            ticket_22: "Menjinakkan Sari Melaka",
            ticket_23: "Menara Langit Pantai",
            ticket_24: "Tur Kota KL",
            ticket_25: "Tur Air Mata Biru di Kuala Selangor",
            ticket_26: "Colmar Tropis",
            ticket_27: "Tur Langkawi",
            ticket_28: "Kuala Selangor yang memberi makan elang",
            ticket_29: "Petrosains, Pusat Penemuan",
            home_title_2: "Cari tahu semua atraksi utama dan",
            home_title_3: "taman hiburan terbaik di Malaysia",
            home_title_4: "Alam & Hidupan Liar di Malaysia",
            ticket_30: "Kebun Binatang Negara",
            ticket_31: "Taman Burung KL",
            ticket_32: "Kebun Binatang Melaka",
            ticket_33: "Kebun Binatang Mini Menara KL",
            ticket_34: "Petualangan Buaya Langkawi",
            ticket_35: "Pertanian di Kota",
            ticket_36: "Peternakan Bentong",
            ticket_37: "Dunia Bawah Laut Langkawi",
            ticket_38: "Entopia oleh Peternakan Kupu-Kupu Penang",
            ticket_39: "Taman Buaya & Rekreasi Melaka",
            home_title_5: "Taman Hiburan & Taman Air Terbaik di Malaysia",
            ticket_40: "Taman Hiburan Berjaya Times Square",
            ticket_41: "LEGOLAND Malaysia",
            ticket_42: "Taman Air Laguna Bayou",
            ticket_43: "99 Taman Negeri Ajaib",
            ticket_44: "Tiket KidZania Kuala Lumpur",
            ticket_45: "VR Universal",
            ticket_46: "Taman Hiburan Escape",
            ticket_47: "Taman Air Petualangan Pantai Desaru",
            ticket_48: "Taman Air Bukit Merah",
            ticket_49: "Taman Air Ehsan",
            ticket_50: "Taman Hiburan I-City",
            ticket_51: "Keluarkan Langkawi",
            home_title_6: "Museum di Malaysia",
            ticket_52: "Museum Makanan Ajaib",
            ticket_53: "Museum Seni 3D Ilusi",
            ticket_54: "Museum Seni Trik 3D Penang",
            ticket_55: "Museum Rumah Gelap",
            ticket_56: "Kubah Teknologi Penang",
            ticket_57: "Museum Hantu Melaka",
            ticket_58: "Negeri Petualangan Ripley",
            ticket_59: "Museum Hantu Penang",
            home_title_7: "Aktivitas Populer di Malaysia",
            ticket_60: "Arung Jeram Kiulu",
            ticket_61: "taman xtreme langkawi",
            ticket_62: "Lompat Jalan Asia",
            ticket_63: "ATV Langkawi",
            ticket_64: "Jelajah Pulau Langkawi",
            home_title_8: "Kapal Pesiar Malaysia",
            ticket_65: "Pelayaran Naga Dickson",
            ticket_66: "Tur & Pelayaran Putrajaya",
            home_title_9: "Layanan transportasi",
            ticket_67: "Tiket KLIA Ekspres",
            ticket_68: "Tiket & Transfer Feri Langkawi",
            ticket_69: "Transfer Bandara Malaysia",
            footer_1: "Unduh aplikasi Headout",
            footer_2: "Dapatkan Bantuan 24/7",
            footer_3: "Berbincanglah dengan kami",
            footer_4: "Hubungi Kami",
            footer_5: "Email Kami",
            footer_6: "Kepala keluar",
            footer_7: "Detail Perusahaan",
            footer_8: "Kebijakan pribadi",
            footer_9: "Ketentuan Penggunaan",
            footer_10: "We Accept",
            footer_11: "© Headout Inc, 82 Nassau St #60351 New York, NY 10038",

            show_inclusions: "Tampilkan Inklusi dan Informasi Penting",
            sunway_ticket_check_availability: "Cek Ketersediaan",
            sunway_ticket_next_available: "Ketersediaan Berikutnya: Hari Ini",
            sunway_ticket_Mobile_ticket: "Tiket Seluler",
            sunway_ticket_Flexible_Duration: "Durasi Fleksibel",
            sunway_ticket_Meals_Included: "Termasuk Makanan",
            sunway_title: "Tiket Taman Hiburan Sunway Lagoon",
            sunway_rating: "(6,5K Ulasan)",
            sunway_header_p: "Headout adalah mitra resmi dan tepercaya dari tempat tersebut, menawarkan pengalaman terpilih untuk menikmati atraksi ini. Ini bukan situs resmi dari tempat tersebut.",
            tickets: "TIKET",
            combos: "KOMBO",
            sunway_ticket_from: "dari",
                
            sunway_ticket_1_title: "Tiket Taman Hiburan Sunway Lagoon",
            sunway_ticket_1_description_1: "Mencari petualangan seru dan menyenangkan bersama keluarga? Kunjungi Sunway Lagoon, yang menawarkan sesuatu untuk segala usia dan preferensi.",
            sunway_ticket_1_description_2: "Nikmati hingga 90 atraksi dan wahana, termasuk Vuvuzela, salah satu seluncuran air tertinggi di dunia, Tomahawk, dan banyak lagi.",
            sunway_ticket_1_description_3: "Jelajahi 6 zona menarik, termasuk taman air, taman hiburan, taman ekstrem, taman satwa liar, taman ketakutan, dan laguna Nickelodeon.",
            sunway_ticket_1_description_4: "Nikmati akses gratis ke Night Park, dengan atraksi dan aktivitas dalam suasana bertema Barat Amerika dan pertunjukan api.",
            sunway_ticket_1_description_5: "Tingkatkan pengalaman Anda dengan akses prioritas opsional ke 21 atraksi, atau pilih pass 2 hari dengan makan, berkemah, dan diskon untuk atraksi berbayar.",
            sunway_ticket_1_skidka: "Diskon 6%",
                
            sunway_ticket_2_title: "Tiket Sunway Lagoon Night Park",
            sunway_ticket_2_description_1: "Siapkan diri Anda untuk malam liar di Sunway Lagoon Night Park, di mana Anda dapat merasakan sensasi Barat Amerika dengan atraksi dan aktivitas bertema koboi yang mengasyikkan!",
            sunway_ticket_2_description_2: "Nikmati pertunjukan api spektakuler dan visual yang menakjubkan sambil merasakan semangat Wild West.",
            sunway_ticket_2_description_3: "Uji keberanian dan keterampilan Anda di wahana Rodéo Bull dan nikmati Grand Canyon River Rapid.",
            sunway_ticket_2_description_4: "Nikmati pertunjukan Wild West Mingle dengan pertunjukan langsung dan hiburan, dan akhiri hari dengan final malam, pertunjukan api spektakuler.",
            sunway_ticket_2_skidka: "Diskon 13%",
                
            sunway_ticket_3_title: "Kombinasi (Hemat 17%): Tiket Aquaria KLCC + Sunway Lagoon",
            sunway_ticket_3_description_1: "Kunjungi dua atraksi paling populer di Kuala Lumpur, Aquaria KLCC dan Sunway Lagoon, dengan satu tiket kombo yang ekonomis.",
            sunway_ticket_3_description_2: "Di Aquaria KLCC, Anda dapat merasakan dunia kehidupan darat dan laut, dengan lebih dari 5.000 makhluk yang dipamerkan.",
            sunway_ticket_3_description_3: "Lihat pameran menakjubkan, termasuk Permata Hutan, Hutan Dalam, Kolam Sentuh, dan Zona Evolusi.",
            sunway_ticket_3_description_4: "Berjalanlah di sepanjang lorong bawah laut sepanjang 90 meter untuk melihat hewan laut yang menakjubkan di habitatnya dan jangan lewatkan aktivitas memberi makan harian.",
            sunway_ticket_3_skidka: "Diskon 17%",
                
            sunway_ticket_4_title: "Kombinasi (Hemat 13%): Tiket Sunway Lagoon Theme Park + Zoo Negara & Pusat Konservasi Panda",
            sunway_ticket_4_description_1: "Hemat uang dengan kombinasi menarik ini yang memberi Anda akses ke sensasi di Sunway Lagoon Park dan penghuni ramah di Zoo Negara.",
            sunway_ticket_4_description_2: "Habiskan hari Anda menjelajahi lebih dari 90 atraksi di salah satu taman hiburan paling ikonik di Malaysia, Sunway Lagoon.",
            sunway_ticket_4_description_3: "Nikmati taman air, taman hiburan, taman ekstrem, taman satwa liar, taman ketakutan, dan laguna Nickelodeon.",
            sunway_ticket_4_description_4: "Jelajahi 110 hektar kehijauan subur sambil menyapa 476 spesies mamalia, burung, reptil, amfibi, dan ikan.",
            sunway_ticket_4_description_5: "Pelajari lebih banyak tentang setiap spesies di Pusat Panda, Rumah Reptil, Kompleks Beruang, Jalan-jalan Savana, dan Kerajaan Mamalia.",
            sunway_ticket_4_skidka: "Diskon 18%",
                
            sunway_ticket_5_title: "Tiket Sunway Lagoon dengan Transfer Pribadi Pulang-Pergi",
            sunway_ticket_5_description_1: "Sunway Lagoon, tujuan hiburan yang luas di Selangor, memiliki sesuatu untuk semua orang. Datanglah dengan persiapan matang, dengan transfer pulang-pergi ke hotel.",
            sunway_ticket_5_description_2: "Dengan tiket ini, akses 6 taman: taman air, taman hiburan, taman satwa liar, taman ekstrem, taman ketakutan, dan laguna Nickelodeon yang hilang.",
            sunway_ticket_5_description_3: "Taman-taman ini memiliki atraksi peluncuran tertinggi di Asia dan zipline terpanjang di Malaysia, serta kebun binatang interaktif pertama di negara tersebut.",
            sunway_ticket_5_description_4: "Ia juga memiliki pantai buatan untuk melengkapi pengalaman berselancar, dengan kolam mengesankan seluas 13.000 m² tempat tamu dapat berselancar.",
            sunway_ticket_5_description_5: "Kolam ombak menggunakan sistem hidrolik yang dipatenkan untuk menciptakan ombak besar setinggi hingga 9 kaki.",
            sunway_ticket_5_skidka: "",
                
            sunway_ticket_6_title: "Kombinasi (Hemat 10%): Tiket Sunway Lagoon Theme Park + Tur Bus Wisata KL Hop-On Hop-Off",
            sunway_ticket_6_description_1: "Dapatkan penghematan dengan kombinasi tiket untuk taman hiburan Sunway Lagoon dan tur bus wisata hop-on-hop-off, menggabungkan sensasi dan eksplorasi kota dengan anggaran terbatas.",
            sunway_ticket_6_description_2: "Nikmati sensasi di taman hiburan Sunway Lagoon, dengan 6 taman unik, termasuk laguna Nickelodeon, taman ketakutan, taman ekstrem, dan lainnya.",
            sunway_ticket_6_description_3: "Berkenalan dengan satwa ramah dan ganas, nikmati petualangan air, dan nikmati wahana seru seperti Pembalasan Bajak Laut dan Tantangan Kongo.",
            sunway_ticket_6_description_4: "Jelajahi Kuala Lumpur dengan tur hop-on-hop-off di 27 pemberhentian, menawarkan fleksibilitas untuk menyesuaikan rute Anda dan menjelajahi kota dalam hanya 1 hari.",
            sunway_ticket_6_description_5: "Nikmati pemandangan kota dari bus bertingkat dua dengan atap terbuka, dilengkapi dengan komentar langsung, dan turun di tempat yang memikat rasa penasaran Anda.",
            sunway_ticket_6_skidka: "Diskon 15%",            
        },
    };

    function translatePage(lang) {
        document.querySelectorAll('[data-translate]').forEach(element => {
            const key = element.getAttribute('data-translate');
            if (translations[lang] && translations[lang][key]) {
                element.textContent = translations[lang][key];
            }
        });
        sessionStorage.setItem('selectedLanguage', lang);
    }

    document.querySelectorAll('.for_perevods1 a').forEach(element => {
        element.addEventListener('click', () => {
            const lang = element.getAttribute('data-lang');
            translatePage(lang);
        });
    });

    const savedLanguage = sessionStorage.getItem('selectedLanguage');
    if (savedLanguage) {
        translatePage(savedLanguage);
    } else {
        const defaultLanguage = 'english'; // Default tilni belgilash
        translatePage(defaultLanguage);
    }
});